development:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
cucumber:
  <<: *test